micronaut:
  application:
    name: todoList
  server:
    port: 9091
#datasources:
#  default:
#    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#    schema-generate: CREATE_DROP
#    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update
index:
  controller:
    path: "/index"

flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false
      url: jdbc:postgresql://127.0.0.1:5432/db-test
      user: postgres
      password: secret
      schemas: mn
      default-schema: mn
datasources:
  default:
    url: jdbc:postgresql://127.0.0.1:5432/db-test
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES
#micronaut-data-jpa
jpa:
  default:
    packages-to-scan:
      - "br.com.micronautpoc.todolist.persistence"
    properties:
      hibernate:
        show_sql: false

kafka:
  bootstrap:
    servers:
      - localhost:9092